### PR TITLE
added winsz message to call TIOCSWINSZ on pty master

### PR DESCRIPTION
**Pull request by noelbk**
I'm using erlexec to run remote terminals, and they need the TIOCSWINSZ ioctl to change the window size.

remote terminals also need a few other things, like setting the TERM environment variable, and that'll be coming up next.

### CODE REVIEW

**Comment by saleyn** [comment]
I am currently on vacation - will review it in a couple of weeks.  This patch causes a failure of the test case above. Is it related to the change?

**Comment by noelbk** [comment]
Hm, worked for me, but let me fix up the unit test.  Have a good vacation!

~~
Noel

**Comment by saleyn** [comment]
@noelbk: did you work on the fix?  The test is still failing.

**Comment by noelbk** [comment]
Ah, finally got the test passing

**Comment by saleyn** [comment]
Thank you for your contribution!

**Comment by noelbk** [comment]
No, thank *YOU* for your project.  There's another patch I use to enable
echo for pty connections so I can use them as remote terminals.  I'll
bundle it up in a bit.

Cheers,
~~
Noel

**Comment by saleyn** [comment]
It would be helpful if you could add a sample use case of the features you added/adding [here](https://github.com/saleyn/erlexec/blob/master/src/overview.edoc#L391).

**Pull request merged**
