### PR TITLE
Make it compile with -std=c++98

### PR DESCRIPTION
**Pull request by kape1395**

### CODE REVIEW

**Comment by saleyn** [comment]
@kape1395 question: in your changes there is no need for the "auto" keyword, is there?

**Comment by kape1395** [comment]
Indeed. I will remove them.

**Comment by saleyn** [comment]
Strange that one test fails after this change - might be that the integration server was overloaded.  May I ask you to repush your PR (e.g. git push YourRemoteRepos +cxx_ansi), to trigger the rerun of tests on Travis CI?

**Comment by kape1395** [comment]
I had to amend my commit to trigger the build. It helped.

**Pull request merged**
