### PR TITLE
Refactor select and poll handling

### PR DESCRIPTION
**Pull request by chrta**
This reduces the amount of ifdefs and should improve readability and maintainability. The functionality is not changed here.

I did not benchmark it, but the tests ran successfully.

### CODE REVIEW

**Comment by saleyn** [comment]
@chrta, thank you very much! I wanted to do the same refactoring over the next weekend! :)

**Comment by chrta** [comment]
Very good :) I also played around with templating CmdInfo, but i did not manage to get it working properly.

**Comment by saleyn** [comment]
The other thing I wanted to have added is the support for unicode commands. If you have spare cycles, feel free to implement. ;)

**Comment by chrta** [comment]
Thank you for the opportunity, but i will pass ;)

**Pull request merged**
